# Generated by Django 5.1.3 on 2024-11-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
