# Generated by Django 5.1.3 on 2024-11-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
