# Generated by Django 5.1.3 on 2024-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_rsvp_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rsvp_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
